### ISSUE TITLE
Support integration with Sentinel

### ISSUE THREAD

**Issue by sczyh30** [spring-cloud-incubator/spring-cloud-circuitbreaker#12]
Hi, I'd like to propose to add [Sentinel](https://github.com/alibaba/Sentinel) integration module (`spring-cloud-circuitbreaker-sentinel`) to `spring-cloud-circuitbreaker`. This includes two parts:

1. non-reactive part: The non-reactive `CircuitBreaker` adapter of Sentinel has been finished. Sentinel has provided an API `SphU.entry(id)` and when it throws `BlockException`, the request is rejected, so I just wrapped the function and fallback with that API. Once I've finished the testing today, a PR will be submitted.
2. reactive part: As for the `ReactiveCircuitBreaker`, currently we're working on the reactive support of Sentinel (will be released in Sentinel 1.5.0 as an adapter module `sentinel-reactor-adapter`). The implementation will resemble this:

```java
public class ReactiveSentinelCircuitBreaker implements ReactiveCircuitBreaker {

    private final String resourceName;

    public ReactiveSentinelCircuitBreaker(String resourceName) {
        this.resourceName = resourceName;
    }

    @Override
    public <T> Mono<T> run(Mono<T> toRun, Function<Throwable, Mono<T>> fallback) {
        return toRun.onErrorResume(fallback)
            .transform(new SentinelReactorTransformer<>(resourceName));
    }
}
```

Once the Sentinel Reactor module is released, we can implement the `SentinelReactiveCircuitBreaker` and test it. The reactive part is expected to be ready in mid-March.

The implementation will follow the interfaces listed in common module (`CircuitBreaker`, `CircuitBreakerFactory` and `ConfigBuilder`).

Would you like to provide some suggestions? :)

**Comment by sczyh30** [comment]
And one more question: I've seen that both `Resilience4JConfigBuilder` and `HystrixConfigBuilder` accepts a circuit breaker config because that config is bound with a certain circuit breaker instance of a certain `id`. But in Sentinel, the circuit breaker and the config (rules) are separate. That is: we can first wrap the circuit breaker with the original function, with no circuit breaking rules initially. When there are no rules, the circuit breaker only records real-time metrics and no circuit breaking will occur. Users can configure and update circuit breaking rules for resources (`id`) at any time via global APIs (e.g. `DegradeRuleManager.loadRules(rules)`) or via the Sentinel dashboard page. 

Thus, there are two kinds of design. The first design (homogeneous with `spring-cloud-circuitbreaker`):

```java
public class SentinelCircuitBreakerConfiguration {
    private String id;
    private List<DegradeRule> rules; // configure the circuit breaker here directly
}
```

The second design (the original design of Sentinel):

```java
public class SentinelCircuitBreakerConfiguration {
    private String id;
    // no config here, only resourceName.
}

// Users configure the rules elsewhere like this:
// Also works for rate limiting, adaptive system protection, etc.
DegradeRuleManager.loadRules(rules);
// In production, we recommend to configure circuit breaking rules via Sentinel dashboard page
// so users even don't need to manually load rules in code
```

So should we follow the first design (homogeneous with `spring-cloud-circuitbreaker`) or the second design?

**Comment by ryanjbaxter** [comment]
@sczyh30 I am in the process of adding another circuit breaker configuration option that allows the application to configure the circuit breaker upon creation.  See https://github.com/spring-cloud-incubator/spring-cloud-circuitbreaker/pull/11

**Comment by sczyh30** [comment]
> @sczyh30 I am in the process of adding another circuit breaker configuration option that allows the application to configure the circuit breaker upon creation. See #11

Nice. I've implemented an initial version of non-reactive Sentinel circuit breaker and submitted a PR: #13. Please review when you're free :)
