### ISSUE TITLE
Resilience4j circuit breaker factory uses single threaded executor

### ISSUE THREAD

**Issue by georgeharley** [spring-cloud-incubator/spring-cloud-circuitbreaker#25]
When using a Resilience4J circuit breaker configured with a timeout I've noticed that if the call to the managed method takes a long time to complete then the request times out as expected but subsequent calls will also time out until the original long running request completes, which was not expected.   

This was seen when using a `Resilience4JCircuitBreakerFactory` to configure a circuit breaker as shown below. A timeout of 2 seconds was specified for the circuit breaker. Not shown below, the method managed/wrapped by the circuit breaker `myMethod()` can be made to sleep for a configurable amount of time in order to simulate a very slow operation. 

```java
    . . .

    @Autowired
    private final CircuitBreakerFactory cbFactory;

    @Bean
    public Customizer<Resilience4JCircuitBreakerFactory> myCBCustomizer() {
        return factory -> factory
                .configure(
                        builder -> builder
                                .circuitBreakerConfig(CircuitBreakerConfig.ofDefaults())
                                .timeLimiterConfig(custom().timeoutDuration(ofMillis(2000)).build())
                                .build(),
                        “myCB”);
    }

    @GetMapping(“/call”)
    public String myHandler() {
        return cbFactory
                .create(“myCB”)
                .run(() -> myMethod(), throwable -> “Fallback response”);
    }

``` 
  
If, when the `@GetMapping` handler is first called, it is arranged for the execution of `myMethod()` to take 10 seconds then the circuit breaker’s timeout of 2 seconds kicks in and the caller gets the “Fallback response” which is great. However, if a new request is immediately sent to the `@GetMapping` handler then the upstream caller also sees a 2 second wait before receiving the “Fallback response” and the managed method `myMethod()` doesn’t seem to be invoked. This keeps happening for all sent requests until 10 seconds have expired since the first call was made. After that the circuit breaker appears to start letting calls through to `myMethod()` once again.  
    
If the above is repeated but the first call to `myMethod()` is made to have a 30 seconds delay then the same behaviour occurs but now all subsequent requests time out with the fallback response until 30 seconds have expired since the first slow request. It looks as if the first request sent to the (deliberately) very slow method appears to block all subsequent requests until the first request eventually completes. 
  
The only thing I can see that _might_ explain this behaviour is the use of a [single thread executor service in the Resilience4JCircuitBreakerFactory](https://github.com/spring-cloud-incubator/spring-cloud-circuitbreaker/blob/master/spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JCircuitBreakerFactory.java#L48). The Javadoc for that method states that it creates an `ExecutorService` that “uses a single worker thread operating off an unbounded queue” and that “no more than one task will be active at any given time.”  
  
What I believe I’m seeing is the very slow first request described above time out from the caller’s perspective but then actually remain running on the executor service’s single worker thread until it eventually completes (10 seconds or 30 seconds later in the above description). All requests that arrive at the circuit breaker’s executor service over that time get queued but never get the chance to actually execute since the circuit breaker times them out.  
  
Changing the choice of executor service in `Resilience4JCircuitBreakerFactory` to be something other than single threaded appears to sort things out and provide what I assume is the expected behaviour. Using a cached thread pool alternative seems to work but there are other options.  
  
Will supply a failing test and a modified `Resilience4JCircuitBreakerFactory` for your consideration in a follow-up PR.

**Comment by ryanjbaxter** [comment]
Closed via 898ca2e
