### ISSUE TITLE
Spring Cloud CircuitBreaker Release

### ISSUE THREAD

**Issue by marmanan** [spring-cloud-incubator/spring-cloud-circuitbreaker#35]
Hi,
We are very interested on including spring cloud circuit breaker as part of our developments, do you have an estimate about when it can be generally available?
Thanks

**Comment by MilgoTest** [comment]
Would like to know the same.

**Comment by ryanjbaxter** [comment]
It will be part of the Hoxton release trail.  For information on when that will happen you can follow this milestone https://github.com/spring-cloud/spring-cloud-release/milestone/68
